baseURL = 'https://ampretia.co.uk/'
languageCode = 'en-gb'
title = 'Ampretia:Dev'

# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "img/Programming1600x400_a.jpg"
  SEOTitle = "Ampretia:Dev Blog Matthew White"
  description = ""
  keyword = "Web, Kubernetes"
  slogan = "All Things Software Development"

  image_404 = "img/Programming1600x400_a.jpg"
  title_404 = "oh bumpers :("
  omit_categories = true

  # leancloud storage for page view counter
  page_view_conter = false 
  leancloud_app_id = ""
  leancloud_app_key = ""



  # Sidebar settings
  sidebar_about_description = "Matthew White. IBM Software Engineer, Photographer, Full Stack Geek, Professional Follower of Rabbit Holes, Human. Views are my own."
  sidebar_avatar = "img/wall-e avatar.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 1 
 
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  # Twikoo comments
  # Follow https://twikoo.js.org/ to set up your own env_id
  twikoo_env_id = ""

  friends = false
  bookmarks = true
  about_me = true

  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [params.social]
  rss            = true 
  #email          = "youremail@gmail.com"
  #facebook      = "full profile url in facebook"
  twitter        = "https://twitter.com/calanais"
  linkedin       = "https://www.linkedin.com/in/matthewbwhiteuk/"
  stackoverflow  = "https://stackoverflow.com/users/1332076/calanais"
  instagram     = "https://www.instagram.com/callanaish/"
  github         = "https://github.com/mbwhite"
  ##wechat         = "your wechat qr code image"
  #medium        = "full profile url in medium"
  #slack         = "full workspace url in slack"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"
  
#  [[params.friend_link]]
#  title = "Linda的博客"
#  href =  "https://zhaozhihan.com"

  [[params.bookmark_link]]
  title =  "Cortex"
  href =  "https://github.com/ampretia/cortex"

#  [[params.bookmark_link]]
#  title = "ServiceMesher"
#  href =  "http://www.servicemesher.com"
#  [[params.bookmark_link]]
#  title =  "Pxhere"
#  href = "https://pxhere.com"
#  [[params.bookmark_link]]
#  title = "unsplash"
#  href = "https://unsplash.com"
  
#  [[params.addtional_menus]]
#  title =  "BOOKS"
#  href =  "/top/books/"


  [[params.addtional_menus]]
  title =  "ARCHIVE"
  href =  "/top/archive/"
  [[params.addtional_menus]]
  title =  "ABOUT🔗"
  href =  "https://calanais.me.uk/"

[permalinks]
  posts = '/:year/:month/:title/'

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "swapoff"

[params.giscus]
  data_repo="ampretia/blog"
  data_repo_id="R_kgDOHRQOhQ"
  data_category="Announcements"
  data_category_id="DIC_kwDOHRQOhc4CPAUr"
  data_mapping="pathname"
  data_reactions_enabled="1"
  data_emit_metadata="0"
  data_theme="light"
  data_lang="en"
  crossorigin="anonymous"